import { Router } from "express";
import BugTypeRoute from "../routes/bugtype.route.js";
import AnnouncementRoutes from "../routes/announcement.route.js";
import ClientRoute from "../routes/client.route.js";
import DepartmentRoute from "../routes/department.route.js";
import DocumentTypeRoute from "../routes/documenttype.route.js";
import EmployeeRoute from "../routes/employee.route.js";
import FollowupRoutes from "../routes/followup.route.js";
import KnowledgeRoute from "../routes/knowledge.route.js";
import LeaveTypeRoute from "../routes/leavetype.route.js";
import ProjectRoute from "../routes/project.route.js";
import RoleRoute from "../routes/role.route.js";
import SalaryHistoryRoute from "../routes/salaryhistory.route.js";
import SubdepartmentRoute from "../routes/subdepartment.route.js";
import TransactionTypeRoute from "../routes/transactionType.route.js";
import TransactionRoute from "../routes/transaction.route.js";
import userRoute from "./user.route.js";
import IndustryTypeRoute from "../routes/industry.route.js";
import ChatRoute from "../routes/chat.route.js";
import MilestoneRoute from "../routes/milestone.route.js";
import AttendanceRoute from "../routes/attendance.route.js";
import LeaveRequestRoutes from "../routes/leaverequest.route.js";
import ProjectKeyRoutes from "../routes/projectkey.route.js";
import TodoRoutes from "../routes/todo.route.js";
import AdminAndAssetsRoutes from "../routes/adminandassets.route.js";

const route = Router();

route.use("/admin-and-assets", AdminAndAssetsRoutes);
route.use("/announcement", AnnouncementRoutes);
route.use("/bug-type", BugTypeRoute);
route.use("/client", ClientRoute);
route.use("/department", DepartmentRoute);
route.use("/document-type", DocumentTypeRoute);
route.use("/employee", EmployeeRoute);
route.use("/followup", FollowupRoutes);
route.use("/leave-type", LeaveTypeRoute);
route.use("/knowledge", KnowledgeRoute);
route.use("/project", ProjectRoute);
route.use("/role", RoleRoute);
route.use("/salary-history", SalaryHistoryRoute);
route.use("/subdepartment", SubdepartmentRoute);
route.use("/transaction-type", TransactionTypeRoute);
route.use("/transaction", TransactionRoute);
route.use("/industry", IndustryTypeRoute);
route.use("/user", userRoute);
route.use("/milestone", MilestoneRoute);
route.use("/attendance", AttendanceRoute);
route.use("/leave-request", LeaveRequestRoutes);
route.use("/credential", ProjectKeyRoutes);
route.use("/todo", TodoRoutes);
route.use("/chat", ChatRoute);

export default route;
